version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: production
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    commit-message:
      prefix: "Upgrade(npm):"
      prefix-development: "Upgrade(dev):"
    reviewers:
      - "evelynhathaway"
    assignees:
      - "evelynhathaway"
